Some general improvements
Desvelao/lualog pull request #1
Opened 2019-03-26 08:17 UTC by DarkWiiPlayer

2019-03-26 17:12 UTC, Desvelao requested changes

2019-03-26 17:12 UTC, Desvelao commented on lualog/util.lua
> +    return and instance.__class_name == class
Remove `and` after return statement. Raise an error this line.

2019-03-26 17:16 UTC, Desvelao requested changes
Fix typos (if you can) in function docs:
- `@tparam` to `@param`
- `@treturn` to `@return`

Thank you for your contribution!

2019-03-27 12:23 UTC, DarkWiiPlayer commented
> Fix typos (if you can) in function docs

`@treturn` and `@tparam` are special [LDoc tags][ldoc] for typed parameters and return values.

Unless you want compatibility with [LuaDoc (Which doesn't know these tags)][luadoc-tags], they are preferable in this case because they specify the the type of the parameter / return value in addition to its description.

[ldoc]: https://stevedonovan.github.io/ldoc/manual/doc.md.html "LDoc"
[luadoc-tags]: http://keplerproject.github.io/luadoc/manual.html#tags "LuaDoc Tags"

2019-03-27 14:59 UTC, Desvelao commented
> > Fix typos (if you can) in function docs
> 
> `@treturn` and `@tparam` are special [LDoc tags](https://stevedonovan.github.io/ldoc/manual/doc.md.html) for typed parameters and return values.
> 
> Unless you want compatibility with [LuaDoc (Which doesn't know these tags)](http://keplerproject.github.io/luadoc/manual.html#tags), they are preferable in this case because they specify the the type of the parameter / return value in addition to its description.

Ok, it's perfect then.

2019-03-28 09:43 UTC, DarkWiiPlayer commented
I'm actually starting to wonder how much sense it really makes to have the `Inspect` class when all it really does is one thing. Wouldn't it just be simpler to have a plain function instead?

2019-03-28 16:58 UTC, Desvelao commented
> I'm actually starting to wonder how much sense it really makes to have the `Inspect` class when all it really does is one thing. Wouldn't it just be simpler to have a plain function instead?

Yes, i guess it would be better. Maybe remove `inpect.lua` file and move the function to `init.lua` as Lualog:inspect(t, options). It would be interesting return self of function to can chain methods.

```lua
function Lualog:inspect(t,options)
   print( inspect_table_function(t, options) ) -- options need to be configured to accept one-time options or self inspect options 
   return self -- to chain methods i mean
end
```

I don't know if it would be interesting accept vararg tables to inspect.

Feel free to try your solution.

2019-04-07 19:01 UTC, DarkWiiPlayer commented
I think for now I'm done with the "general" improvements. I may have a go at turning inspect into a single function, though it's not like there's anything wrong with the object-oriented approach either.

Feel free to review and merge <3

2019-04-08 13:43 UTC, merged

2019-04-08 13:44 UTC, Desvelao commented
Perfect! Thank you! ;)